### PR TITLE
Ensure files opened are also closed

### PR DESCRIPTION
**Pull request by jkburges**
Otherwise, we get a resource leakage, with no way of callers to fix. The can stop certain operations on files later (e.g. delete/move) because there's still an open handle to them from here.

### CODE REVIEW

**Comment by pointlessone** [comment]
Let's take the approach taken in prawnpdf/prawn#1090. For consistency.

**Comment by jkburges** [comment]
Given that `TTFunk::File.verify_and_open` https://github.com/prawnpdf/ttfunk/blob/master/lib/ttfunk.rb#L25 is public, I could keep that method and introduce a new one `verify_and_read` which delegates most functionality to it - thereby keeping the public API the same, or, I could just rename the existing method - changes the API but probably cleaner if you're not concerned about it.

What's better in your opinion?

**Comment by jkburges** [comment]
I went with the latter from above (I don't _think_ `verify_and_open/read` is intended for public use).

**Comment by petergoldstein** [comment]
@pointlessone This looks fine to me, and consistent with the approach taken in `prawnpdf/prawn`.  Your thoughts?

I don't see any dependencies on the renamed method in `prawn`, so I think renaming it is acceptable.

**Review by gettalong — COMMENTED** [review]
Looks good to me and agree with @petergoldstein on renaming.

**Comment by pointlessone** [comment]
TTFunk is used by other gems (and maybe apps, too). I don't know if any of them are using this particular method but since it's a public API I'd keep it around. I suggest we keep and deprecate `verify_and_open` (with a warning) in addition to adding `verify_and_read`.

**Comment by pointlessone** [comment]
This has been merged in git. Thank you for your contribution.

**Pull request closed without merging**
