### PR TITLE
Improve Performance of TTFunk::Table::OS2#group_original_code_points_by_bit

### LINKED ISSUE #82: Performance Problem: TTFunk::Subset#encode 30x slower than v1.5.1
## Problem

In v1.6.2.1, `TTFunk::Subset#encode` takes about 30x longer than v1.5.1.

## Reproduction Code

```ruby
require 'ttfunk'
require 'benchmark'

# English Font
file = TTFunk::File.open("DejaVuSans.ttf")
# Japanese Font
# file = TTFunk::File.open("GenShinGothic-Normal.ttf")

subset = TTFunk::Subset.for(file, :unicode)
Benchmark.bmbm { |x| x.report('encode') { 10.times { subset.encode } } }
```

## Results

|ttfunk version|font|time[s]|
|---|---|---|
|v1.5.1|DejaVuSans.ttf|0.035328|
|v1.6.2.1|DejaVuSans.ttf|1.336027|
|v1.5.1|GenShinGothic-Normal.ttf|0.161720|
|v1.6.2.1|GenShinGothic-Normal.ttf|4.500678|

## Profile

[TTFunk::Table::OS2.group_original_code_points_by_bit](https://github.com/prawnpdf/ttfunk/blob/master/lib/ttfunk/table/os2.rb#L271-L282) and `TTFunk::Table::OS2.group_original_code_points_by_bit` took a lot of time in stackprof profile.

### PR DESCRIPTION
**Pull request by kokuyouwind**
## Abstruct

fix #82

Original code takes `O(N * M)` time  where N is UNICODE_RANGES size and M is code_map keys size.
Improved code takes `O(max(N, M))` time.

## Idea

Original code calls `r.cover?` with all pair of `UNICODE_RANGES` and `code_map keys`.
This takes `O(N * M)` time.

If `UNICODE_RANGES` and `code_map keys` are both sorted, first `UNICODE_RANGE` contains some `code_map keys` of the head flagment (or empty), next `UNICODE_RANGE` contains next flagment, and so on.
This storategy loops `UNICODE_RANGES` and `code_map keys` indivisualy, so it takes `O(max(N, M))` time.

## Performance Test Result

I measure `Problem: TTFunk::Subset#encode` time with #82 reproduction code.(English Font changed to 'spec/fonts/DejaVuSans.ttf')
It's about 8x faster than master branch, still 4x slower than 1.5.1 branch.

|branch|font|time[s]|
|---|---|---|
|master|DejaVuSans.ttf|0.451248sec|
|this branch|DejaVuSans.ttf|0.077370sec|
|(reference)1.5.1|DejaVuSans.ttf|0.021442sec|
|master|GenShinGothic-Normal.ttf|1.706043sec|
|this branch|GenShinGothic-Normal.ttf|0.220942sec|
|(reference)1.5.1|GenShinGothic-Normal.ttf|0.064324sec|

### CODE REVIEW

**Comment by pointlessone** [comment]
@kokuyouwind Thank you for your contribution. The numbers look great.

@camertron Could you please take a quick look?

**Comment by f440** [comment]
@pointlessone

is there any progress? i'm looking forward to merging this fix🥺

**Review by pointlessone — APPROVED** [review]

**Comment by pointlessone** [comment]
@kokuyouwind Could you please rebase your branch on top of the current master?

**Comment by kokuyouwind** [comment]
@pointlessone OK, rebased.

**Comment by shrkw** [comment]
@pointlessone @camertron or somebody authorized,
Hi, would you please merge this PR?

**Pull request merged**
