### PR TITLE
Parse bitmap data from sbix tables

### PR DESCRIPTION
**Pull request by javan**
I set out to find an effective way of extracting emoji images from Apple's "Apple Color Emoji.ttf" font and found that the data necessary data is in the [sbix table](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html).

> This table provides access to bitmap data in a standard graphics format (such as PNG, JPEG, TIFF).

``` ruby
emoji_font = Pathname.new("/System/Library/Fonts/Apple Color Emoji.ttf")
ttf = TTFunk::File.open(emoji_font)

char_code = "\u{1f4a9}".codepoints.first
glyph_id = ttf.cmap.unicode.first.code_map[char_code]

ttf.sbix.all_bitmap_data_for(glyph_id).each do |bitmap|
  filename = "glyph-#{glyph_id}-#{bitmap.ppem}.#{bitmap.type}"
  File.write(filename, bitmap.data.read)
end
```

glyph-569-160glyph-569-96glyph-569-64glyph-569-48glyph-569-40glyph-569-32glyph-569-20

### CODE REVIEW

**Comment by tremby** [comment]
I'm trying to shoehorn the [Android emoji font](https://android.googlesource.com/platform/external/noto-fonts/+/master/other/NotoColorEmoji.ttf) into this. I'm not having any luck. I don't know anything about TTF fonts: is it maybe the same issue as above, with this font not having an sbix table?

**Comment by Danny182** [comment]
I'm trying to do extract all the emojis with TTFunk but can't find the way. Can someone help me. What do I have to run from the terminal after installing the gem TTFunk?

**Comment by pointlessone** [comment]
@Danny182 You can take a look at [sbix table specs](https://github.com/prawnpdf/ttfunk/blob/f2ec535630fe246a8bbe2ed45dea6d93620aed5e/spec/integration/file_spec.rb#L119-L146)

**Comment by Danny182** [comment]
@pointlessone , thank you for the reply.
I didn't understand how to run the code. If I run "ruby file_spec.rb" I get the missing "spec_helper.rb". If I run that one I get another missing one. 
Sorry but I'm having problems to run the "Rakefile".

**Comment by pointlessone** [comment]
@Danny182 That code won't extract anything for you. That is merely an example of usage. You would need to write your own code to actually extract emoji.

The file is not a "Rakefile". It's a spec file meant to be run with RSpec. Try `rspec spec/integration/file_spec.rb` to run it but I'm not sure how that might be helpful to you.

**Comment by Danny182** [comment]
I found a way. By running "gemoji"
by terminal running "rake images:extract" it extracts the emojis but it doesn't extracts some of them. 
"🙄 1F644" doesn't get extracted. I updated manually the "db/NamesList.txt" (the info of that emoji is in there). 
Can someone help me?

Thanks in advance
@pointlessone @javan

**Pull request merged**
